### ISSUE TITLE
"VoiceMaster" functionality

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/Esports-Bot-Rewrite#15]
Bot should create/adopt/assign a voice channel then, when people join it, create a new, temporary voice channel and move the joiner into it. Channel should disappear once there is no one left in it.

**Comment by Trimatix** [comment]
Implemented: https://github.com/FragSoc/Esports-Bot-Rewrite/commit/9adbfaed9032eafa0c8270f215ae86f3c46d2566
