### ISSUE TITLE
[Bug] `!pingme create-role` closed immediately

### ISSUE THREAD

**Issue by Trimatix** [FragSoc/Esports-Bot-Rewrite#220]
**Describe the bug**
I made a role poll but after roughly 5 seconds the poll ended

**Steps to reproduce**
1. `!pingme create-role Titanfall 2`
2. Wait a few seconds
3. Observe poll ending early

**Message link**
https://discord.com/channels/213011069671571456/213015673167806474/940280312422891611

**Comment by Fluxticks** [comment]
This is working as intended, the final argument of "poll length" is an optional arg and defaults to 300 seconds. You need to put the role name in quotes, ie "Titanfall 2" as otherwise it takes the poll length to be 2 seconds
